### PR TITLE
Fix #234

### LINKED ISSUE #234: Type names are classified as storage.type instead of entity.name.type
## Details

What editor are you seeing the problem in? VSCode

## The problem

Referenced typenames are classified as `storage.type`. However, I noticed that this causes incoherent highlighting in many colorschemes, since I believe the guidelines say that `storage.type` are for things like `class` and `struct`. A typename would be classified by `entity.name.type{.class}`.

Is this a conscious decision? If not I'd willing to provide a PR to change this.

image

### PR DESCRIPTION
**Pull request by chtenb**
I noticed that the compile step gave errors about the changes. Should I do anything manually to fix that?

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/csharp-tmLanguage?pullRequest=235) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/csharp-tmLanguage?pullRequest=235) before we can accept your contribution.<br/><br/>:x: chtenb [sign now](https://cla.dotnetfoundation.org/dotnet/csharp-tmLanguage?pullRequest=235)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/csharp-tmLanguage?pullRequest=235) it.</sub>

**Comment by JoeRobich** [comment]
> I noticed that the compile step gave errors about the changes. Should I do anything manually to fix that?

Yeah, will need to fix up any of the failing test that are still validating the previous behavior.

**Comment by chtenb** [comment]
@JoeRobich Tests fixed

**Comment by JoeRobich** [comment]
@chtenb Thanks!

**Review by JoeRobich — APPROVED** [review]

**Pull request merged**
